# Generated by Django 3.2.25 on 2024-06-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='user',
            name='caloric_needs',
            field=models.FloatField(blank=True, default='1600', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        )
       
    ]
