# Generated by Django 3.2.18 on 2024-07-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.CharField(choices=[('Sedentary', 'Sedentary (little or no exercise)'), ('Lightly active', 'Lightly active (light exercise/sports 1-3 days/week)'), ('Moderately active', 'Moderately active (moderate exercise/sports 3-5 days/week)'), ('Very active', 'Very active (hard exercise/sports 6-7 days a week)'), ('Super active', 'Super active (very hard exercise/physical job & exercise 2x/day)')], default='Sedentary', max_length=20),
        ),
    ]
