# Generated by Django 3.2.25 on 2024-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240630_1538'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='user',
            name='caloric_needs',
            field=models.FloatField(blank=True, null=True),
        )
    ]
