# Generated by Django 3.2.25 on 2024-06-30 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240630_1553'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.user'),
            preserve_default=False,
        ),
   
        
        migrations.AddField(
            model_name='user',
            name='payment_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
      
        migrations.AlterField(
            model_name='payment',
            name='duration',
            field=models.IntegerField(help_text='Duration in months'),
        ),
    ]
